### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by dmonad** [yjs/y-crdt#2]
# Milestone 1 
- [ ] #6 Implementation of the Yjs update format + differential updates which was not in the initial work description.

* Implement the API described in https://docs.yjs.dev/api/document-updates
* Testing: Create a script that generates Yjs documents based on a seed number. Read these encoded Yjs documents with Yrs' update API and encode them again. The documents should contain the same content.

# Milestone 2

* Implementation of the shared types API (read & write API). We get as far as we get. We won't be able to implement all features (the delta format & event system is quite complicated). Additionally to the original work description, we will plan to calculate the differences after a transaction is finished.

# Milestone 3
• Port to WASM and create language bindings for Python. The python bindings weren't in the original work description. 
• Performance analysis compared to Yjs and Automerge

**Comment by Horusiath** [comment]
Regarding M1:

### `Y.applyUpdate(Y.Doc, update:Uint8Array, [transactionOrigin:any])`

Proposed API:

```rust
impl Doc {
  /// D is implemented by DecoderV1 or DecoderV2, eg.:
  /// ```rust
  /// let mut decoder = DecoverV1::new(binary);
  /// let mut doc = Doc::new();
  /// doc.apply_update(&mut decoder)?;
  /// ```
  pub fn apply_update<D: Decoder>(&mut self, decoder: &mut D) -> Result<()>;
}
```

Rationale: in Rust there's no sense in making static methods that operate over specific local variables eg. `doc.apply_update(decoder)` is the same thing as `Doc::apply_update(doc, decoder)`. I also proposed using generics, as Rust will recognize them at call site and devirtualize. Downside of that approach is that generics cannot be exposed in WASM and C FFI. For that, we could work around different decoder version with:

```rust
pub enum Decoder { 
  V1(DecoderV1), 
  V2(DecoderV2) 
}

impl Doc {
  pub fn apply_update(&mut self, &mut decoder: Decoder) -> Result<()>;
}
```
I don't know about all possible use cases of `transactionOrigin`, so I didn't include it in the API.

### `Y.encodeStateAsUpdate(Y.Doc, [encodedTargetStateVector:Uint8Array]): Uint8Array`

Would it be plausible to separate principles like update generation from serialization/deserialization?

```rust
impl Doc {
  pub fn get_updates_since(&self, version: &StateVector) -> Vec<Update>;
}

// Update implements Encode
pub struct Update {
  client_blocks: Vec<Block>,
  delete_set: DeleteSet,
}

let version = StateVector::decode(&mut decoderV1);
let doc = Doc::new();
let updates = doc.get_updates_since(version);
let mut output = Vec::new();
let mut encoder = EncoderV1::new(&mut output);
updates.encode(encoder);
```

### `Y.encodeStateVector(Y.Doc): Uint8Array`

Similar as above?

```rust
impl Doc {
  pub fn state_vector(&self) -> &StateVector;
}

let doc = Doc::new();
let version = doc.state_vector();
let mut output = Vec::new();
let mut encoder = EncoderV1::new(&mut output);
version.encode(encoder);
```

I admit it's way easier to test them this way.

### `ydoc.on('update', eventHandler: function(update: Uint8Array, origin: any, doc: Y.Doc))`

I must admit that I have the most problems thinking about this one. Rust is well known of using safe approach to pub/sub mechanics via introduction of [Streams](https://rust-lang.github.io/async-book/05_streams/01_chapter.html). However streams all pull-based, while Observables/EventHandlers represent push-based paradigm. However given C FFI and WASM support, we probably should just go with callback support. Therefore proposed API: 

```rust
impl Doc {
  pub fn on_update<F: : Fn(&[u8], &Doc)->()>(&mut self, fn: F) -> Subscription
}
```

`Subscription` here implements drop trait &rarr; droping subscription object works as unsubscribe. Since I'm not sure what origin could, be I left it unrepresented.

### `Y.logUpdate(Uint8Array)`
