### ISSUE TITLE
Meaning of polyfils

### ISSUE THREAD

**Issue by Horusiath** [yjs/y-crdt#27]
I'm looking at https://github.com/yjs/y-crdt/blob/main/yrs-api-wrapper/src/lib.rs and try to figure out how to implement these polyfil methods:

```rust
// By merge updates we mean merge full docs, updates or updates + delete sets?
fn merge_updates(updates: &[&[u8]]) -> Vec<u8>;

// Updates don't have state vectors, documents do.
fn encode_state_vector_from_update(_update: &[u8]) -> Vec<u8>;

// Again updates don't have state vectors.
fn diff_updates(update: &[u8], _state_vector: &[u8]) -> Vec<u8>;
```

The names are not self-explanatory, as they seem to conflate the concepts fo updates, documents and delete sets.

**Comment by dmonad** [comment]
These functions basically mirror the "alternative updates API" described here: https://docs.yjs.dev/api/document-updates#alternative-update-api

In Yjs, the idea is that you can synchronize documents without transforming them to a Yjs document first. This API is used by the browser and by the server to perform performant merges when it is not necessary to actually read the content. With Yrs, it should be fine to transform them to a BlockStore first, perform the merge and re-encode them to binary again. 

Once we have this, we can plug Ywasm into the Yjs test-suite as well.

**Comment by dmonad** [comment]
Just to clarify, a document update can be an encoded Y document, or just an incremental update. There is just one update format in Yjs. It always contains blocks and a delete set.

**Comment by Horusiath** [comment]
> Just to clarify, a document update can be an encoded Y document, or just an incremental update. There is just one update format in Yjs. It always contains blocks and a delete set.

Except that when you don't know if you're dealing with document, then you need to apply/integrate updates instead of just deserializing the content.

Also, why is this API used in y-py? If we have access to Rust, we can use all the power of C FFI, including things like events subscriptions or using document pointers right away? No need to go through deserialize/serialize cycle on every operation.

**Comment by dmonad** [comment]
While the client wants to make use of subscriptions and all the other features that Yrs provides, the server really doesn't need these features. We just need a stable API. The subscription system will probably change a lot in the future.

About the existence of the API in Yjs: Most servers don't need to understand the content of the document. One advantage of the "alternative updates API" is that `mergeUpdates([initialState, update])` is more performant than `Y.applyUpdate(ydoc, initialState); Y.applyUpdate(ydoc, update)` because the former doesn't create a YDoc, and doesn't need to integrate structs (it is simply deserializing and serializing in the correct order while ignoring duplicates). We will store the document directly in the database and write the merged update back. For a server that needs to synchronize hundreds of thousands of documents, it is not desirable to keep the documents in memory.

I'm aware that the current implementation of Yrs is not able to merge updates without integration. But we will get there at some point. Until then, we have a stable API to work against.

>  No need to go through deserialize/serialize cycle on every operation.

The database providers in Yjs solve this problem by caching `N` incremental updates in the database and merge these updates once we have more than `N` updates.
