### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by davidbrochart** [yjs/y-crdt#48]
I'm trying to package `y-py` for `conda-forge` in https://github.com/conda-forge/staged-recipes/pull/17076. The package is build from sources. In order to trigger the build for new versions, a tag must be applied to the GitHub repository.
Would it be possible to tag `0.1.3`?

**Comment by dmonad** [comment]
Sure! I created a tag manually. 

Does the format of the tag matter?

**Comment by dmonad** [comment]
I can create a new tag with every release. Do you have to manually publish on conda or does that happen automatically?

**Comment by davidbrochart** [comment]
> Does the format of the tag matter?

No, the one you created is fine, it just has to be consistent with how conda-forge parses the source URL. Note that a tag is enough (no need for a GH release).

> I can create a new tag with every release. Do you have to manually publish on conda or does that happen automatically?

The conda-forge bot will automatically publish a new package when a new tag is created. One just has to merge if tests pass, but even that can be automated.

One thing I was wondering though, is there going to be a global versioning scheme for the whole repository? This means if only the y-py bindings change, the rest will be tagged too (I guess there will be more language bindings in the future).

Thanks!

**Comment by dmonad** [comment]
> One thing I was wondering though, is there going to be a global versioning scheme for the whole repository? This means if only the y-py bindings change, the rest will be tagged too (I guess there will be more language bindings in the future).

Yes, that's the plan. In order to avoid confusion, every package should automatically be bumped when one package is released. It should be obvious that if you are using y-py v0.1.3, you are using yrs v0.1.3. 

For now, we will release manually when needed. But I guess that we will, at some point, have weekly or monthly releases where we publish all packages. Bugfixes might be released under special alpha tags (e.g. ypy-v0.1.5-0 if we fixed an issue in y-py and we don't want to publish all packages before the monthly release).

Let me know if you want to write some automation in the y-crdt project. We already have an automatic publishing script for y-py on pypi. 

I'm closing this issue, but feel free to continue discussing.

**Comment by davidbrochart** [comment]
> Let me know if you want to write some automation in the y-crdt project. We already have an automatic publishing script for y-py on pypi.

[Jupyter Releaser](https://github.com/jupyter-server/jupyter_releaser) is a tool to automate the publishing of packages, using GitHub actions, and despite its name it can be used for general PyPI and NPM packages. It doesn't support Cargo, but maybe that could be an improvement.

**Comment by dmonad** [comment]
Thanks for the link! 

We probably would need to adapt it to first generate the python bundle before running the usual script.

We should talk about this at some point. I'd prefer not to have too many external dependencies because that will make maintaining much harder when things are breaking regularly. Ideally, we just extend the existing script.
