### ISSUE TITLE
Nightly Rust really needed?

### ISSUE THREAD

**Issue by davidbrochart** [yjs/y-crdt#49]
Does y-crdt really need Rust nightly? This makes it harder to package e.g. in conda-forge.

**Comment by dmonad** [comment]
The project currently doesn't compile without Rust nightly. I remember that there is a feature in the nightly branch that we can't easily do without.

But we want to migrate to the stable branch as soon as this feature is merged. 

@Horusiath what was that feature again and when will it be shipped into the stable channel?

**Comment by Horusiath** [comment]
I'll take a look at it - originally it was needed due to `new_uninit` and `map_entry_replace` features of nightly compiler. I need to check them out if we still need them.

**Comment by Horusiath** [comment]
Update: we need a `#![feature(map_entry_replace)]` because it's used for delete store merging [here](https://github.com/yjs/y-crdt/blob/df009c1a5e398ef27e6a6beb8aa00908faa2edfe/yrs/src/id_set.rs#L300). I'll try to think how to remove the dependency on it.

Another thing is that #54 is using `smallstr` package - which ideally should work with `feature=["union"]` set for the best performance, and this feature requires nightly compiler as well.
